### PR TITLE
Viewmode tabular: Make columns mandatory

### LINKED ISSUE #823: List views with `tabular` view mode are broken
## Describe the bug

Using the `tabular` view mode without providing custom columns causes PHP fatal error.
Bildschirmfoto 2023-07-28 um 13 53 55

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #823

### CODE REVIEW

File: library/Icingadb/Widget/ItemTable/StateItemTable.php [hunk 1]
```diff
@@ -4,6 +4,7 @@
 
 namespace Icinga\Module\Icingadb\Widget\ItemTable;
 
+use Icinga\Exception\MissingParameterException;
```
Comment (nilmerg) [inline library/Icingadb/Widget/ItemTable/StateItemTable.php:7]: remove this

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
