### PR TITLE
ContinueWith: Disable button if the query with filter returns no results

### LINKED ISSUE #1299: Filter bulk action `Continue with` shows an empty detail page
Image

## To Reproduce
1. Add a non-matching search bar filter so that the Continue with button becomes enabled.
2. Ensure the filtered list is empty.
3. Click the Continue with button to open the detail view.
4. All action buttons in the detail view now throw an error.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #1299 

requires https://github.com/Icinga/ipl-web/pull/334

### CODE REVIEW

File: library/Icingadb/Common/SearchControls.php [hunk 1]
```diff
@@ -51,14 +51,24 @@ public function createSearchBar(Query $query, ...$params): SearchBar
      *
      * @param Url $detailsUrl
      * @param SearchBar $searchBar
+     * @param bool $hasResults Whether the current query has results
      *
      * @return ContinueWith
      */
-    public function createContinueWith(Url $detailsUrl, SearchBar $searchBar): ContinueWith
+    public function createContinueWith(Url $detailsUrl, SearchBar $searchBar, bool $hasResults): ContinueWith
```
Comment (nilmerg) [inline library/Icingadb/Common/SearchControls.php]: Default the new parameter to `true` here. This trait is used by the graphite module and dependencies, but while they don't call `createContinueWith`, it's a perfect example why backwards compatibility matters: Because they *could have* called it.

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
